### ISSUE TITLE
Camera Jacker does not work after Resolution Change

### ISSUE THREAD

**Issue by UiharuKazari2008** [Dervali-git/Dervali-VRCMods#1]
When using VirtualCamera2 (Avatar Camera with a Camera Jacker) after resolution change the camera not capturing the image from virtual camera even though its visible on the camera preview

**Comment by Dervali-git** [comment]
This is due to some hard coded values in the camera jacker shader. It is possible to change those values to allow 4k to work, unfortunately causes massive lag in many worlds.

I recommend using VRC Lens instead https://booth.pm/ja/items/2283183
