### ISSUE TITLE
NearClippingPlaneAdjuster causes crash

### ISSUE THREAD

**Issue by GenesisAria** [Dervali-git/Dervali-VRCMods#4]
Not immediately, but after a few seconds it causes vrc to vanish.

**Comment by Dervali-git** [comment]
Are you using emmVRC? If not, what other mods do you have loaded?

**Comment by Dervali-git** [comment]
Try installing Advanced Safety https://github.com/knah/VRCMods/releases/tag/updates-2020-10-28
That seems to prevent the crashing with emmVRC and certain mods.
